### ISSUE TITLE
Configuration Change Absturz.

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#60]
Split #55 

```
... Absturz nachdem ich im Detail auf Karte gegangen bin (hier war der aktuelle Standort aber richtig angezeigt)
```
# Steps
- Settings
- Datenaktualisierung
- Zurück zur Übersicht
- App in den Hintergrund
- App in den Vordergrund
# Expected result
- App läuft weiter
# Actual result
- App stürzt ab
# Bemerkung

Ein Problem, das durch die Synchronisation sichtbar wird. Es handelt sich im Android-Shargon um ein Problem des Typs "Configuration Change", also zum Beispiel Screen-Rotation, App in den Hintergrund/Vordergrund verschieben etc.
Die Vermutung ist, dass es Abstürze dieser Art noch an anderen Stellen gibt. Diese können aber nur durch vollständiges Testing der App erkannt werden

Stacktrace aus der Developer-Console:
https://play.google.com/apps/publish/?dev_acc=15160088022255091383#ErrorClusterDetailsPlace:p=ch.bfh.ti.risis.particip&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=SettingsFragment.java&tc=ch.bfh.ti.risis.particip.SettingsFragment&tm=syncDone&nid&an&c&s=new_status_desc&ed=0

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
    at ch.bfh.ti.risis.particip.SettingsFragment.syncDone(SettingsFragment.java:211)
    at ch.bfh.ti.risis.particip.SettingsFragment.access$lambda$0(SettingsFragment.java)
    at ch.bfh.ti.risis.particip.SettingsFragment$$Lambda$1.accept(Unknown Source)
    at ch.bfh.ti.risis.particip.service.impl.SynchronizationServiceImpl.lambda$notifyListeners$19(SynchronizationServiceImpl.java:119)
    at ch.bfh.ti.risis.particip.service.impl.SynchronizationServiceImpl.access$lambda$3(SynchronizationServiceImpl.java)
    at ch.bfh.ti.risis.particip.service.impl.SynchronizationServiceImpl$$Lambda$4.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5373)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

```

**Comment by Kristinaherbst** [comment]
Wäre es an mir die App vollständig zu testen? Oder wie wird das gemacht? Ich habe alle möglichen Navigationswege getestet.

**Comment by ukeller** [comment]
Gehört zu #65

**Comment by ukeller** [comment]
Bitte prüfen.

**Comment by Kristinaherbst** [comment]
bisher gab es noch keinen weiteren Absturz
